name: Build Tests
on: [pull_request]
jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {
            name: "Windows/X64/",
            os: self-hosted,
            args: -G Ninja,
          }
    steps:
      - uses: actions/checkout@v3     
      - run: git submodule update --init --recursive
      - run: |
          cmake ${{ matrix.config.cmake_extra_args }} -S . -B ./build
          cd build
          ninja
