name: Build Tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {
            name: "Linux/X64/",
            os: ubuntu-latest,
            generator: "Unix Makefiles"
          }
          - {
            name: "Windows/X64/",
            os: windows-latest,
            generator: "Visual Studio 16 2019"
          }
    steps:
      - name: Checkout code
        uses: actions/checkout@v3    
        
      - name: Build project
        run: |
          cmake -S . -B ./build -G "${{ matrix.config.generator }}"
          cmake --build ./build
